### ISSUE TITLE
Error in push to pach

### ISSUE THREAD

**Issue by yanpozka** [dwhitena/slides#2]
Just playing with your examples, thanks all them !!
and I got this error in **pushtopach** example. It seems the signature for _StartCommit()_ function has been changed

```
slides/gophercon2016/code/pushtopach/pushtopach.go:50: too many arguments in call to c.StartCommit
```

**Comment by dwhitena** [comment]
Thanks @yanpozka.  Sorry it has taken so long to get to this.  I'm updating things now, and will try to resolve this.  A more up-to-date version, that you would be interested in, is here: https://blog.gopheracademy.com/advent-2016/pachyderm/

**Comment by yanpozka** [comment]
awesome, thanks for your answer
